### ISSUE TITLE
Unable to access PrestaShop 1.6.1.1 API - 401 Unauthorized  

### ISSUE THREAD

**Issue by ishgoel** [Bukimedia/PrestaSharp#177] opened 2015-12-06 08:12 UTC
Hi!
I have full permissions to PrestaShop and I am trying to access OrderFactory using PrestaSharp with following code:

```
string BaseUrl = "http://www.example.com/api";
string Account = ".....APIKeyHere....";
string Password = "";
OrderFactory OrderFact = new OrderFactory(BaseUrl, Account, Password);
order ps_order = OrderFact.Get(1);
```

But the above code gives a 401 Unauthorized error each time. 
Please help!

**Comment by EduLeonPavon** [comment] 2015-12-06 16:07
Hello @ishgoel 
Could you paste the table permissions of the web service?
Thank you.

**Comment by ishgoel** [comment] 2015-12-06 16:59
Hi there!
Please see the attachment.

Thanks
Ish

On Sun, Dec 6, 2015 at 9:37 PM, Eduardo León Pavón <notifications@github.com

**Comment by nabilbo** [comment] 2016-03-19 11:44
I get the same error ...
i checked my web service permission...

**Comment by nabilbo** [comment] 2016-03-19 15:02
I had same error 
but resolved by configuring my OVH hosting parameters (PHP in CGI mode enabled)

**Comment by javinievas** [comment] 2016-06-02 10:02
Just create an .htaccess with that content:

<IfModule mod_rewrite.c>
RewriteEngine on
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
</IfModule>

And it works. The problem is related to how fcgi works.

Hope this helps.

**Comment by titodevera** [comment] 2019-08-09 07:23
> Just create an .htaccess with that content:
> 
> <IfModule mod_rewrite.c>
> RewriteEngine on
> RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
> </IfModule>
> 
> And it works. The problem is related to how fcgi works.
> 
> Hope this helps.

It works in my Prestashop 1.7.6 + FastCGI ! Thank you!

**Closed** 2023-11-12 16:45 UTC
Labels: question
